name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of Files
        run: |
          pwd
          ls
      - name: Checkout
      - name: List of Files After checkout
        run: |
          pwd
          ls
        uses: action/checkout@v1
      - name: Simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1 # pode referenciar actions externo
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"